### ISSUE TITLE
ModuleNotFoundError: No module named 'ez_storage'

### ISSUE THREAD

**Issue by etherealxx** [Lainupcomputer/stable-diffusion-webui-random_prompt_generator#6]
Still exist even after i install ez_storage manually
```
Error loading script: extension.py
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "F:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\stable-diffusion-webui\extensions\stable-diffusion-webui-random_prompt_generator\scripts\extension.py", line 4, in <module>
    from scripts.generator import Generator
  File "F:\stable-diffusion-webui\extensions\stable-diffusion-webui-random_prompt_generator\scripts\generator.py", line 2, in <module>
    from ez_storage.ez_storage import Ez_Storage
ModuleNotFoundError: No module named 'ez_storage'

Error loading script: generator.py
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "F:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\stable-diffusion-webui\extensions\stable-diffusion-webui-random_prompt_generator\scripts\generator.py", line 2, in <module>
    from ez_storage.ez_storage import Ez_Storage
ModuleNotFoundError: No module named 'ez_storage'
```

**Comment by Lainupcomputer** [comment]
have you checked if "ez_storage-1.3.3.dist-info" and "ez_storage" are located in your venv ? 
`\stable-diffusion-webui\venv\Lib\site-packages`
You can download the lib manualy [Here](https://github.com/Lainupcomputer/ez-storage/tree/master/src)

**Comment by etherealxx** [comment]
![2023-02-07 17_43_40-Logan Paul Cancels Himself With Horrible Response Video - YouTube](https://user-images.githubusercontent.com/64251396/217224921-7d8870b1-b387-44a0-b4bb-b134f1254948.jpg)
it says it's downloaded, but it is not. Though your method of downloading the lib manually works, you need to figure out how to install that automatically. You can close this issue then.
